export const staffRoles = ["SUPER_ADMIN", "STAFF", "FIELD", "PREP", "FINANCE", "SUPPORT", "VIEWER"] as const;

export type StaffRole = (typeof staffRoles)[number];

export const permissions = [
  "lead.view",
  "lead.edit",
  "inbox.view",
  "inbox.reply",
  "inbox.manage",
  "reservation.view",
  "reservation.create",
  "reservation.edit",
  "reservation.cancel",
  "reservation.assign_vehicle",
  "customer.view_basic",
  "customer.view_sensitive",
  "customer.edit",
  "vehicle.view",
  "vehicle.edit",
  "vehicle.inspect",
  "handover.override",
  "prep.view",
  "prep.manage",
  "payment.view",
  "payment.capture",
  "payment.refund",
  "finance.view",
  "finance.review",
  "finance.export",
  "finance.approve",
  "pricing.view",
  "pricing.edit",
  "staff.view",
  "staff.manage",
  "settings.manage",
  "audit.view",
  "ratings.view",
  "investor.view",
  "investor.manage",
  "investor.finance",
] as const;

export type Permission = (typeof permissions)[number];

const rolePermissions: Record<StaffRole, readonly Permission[]> = {
  SUPER_ADMIN: permissions,
  STAFF: [
    "lead.view",
    "lead.edit",
    "inbox.view",
    "inbox.reply",
    "inbox.manage",
    "reservation.view",
    "reservation.create",
    "reservation.edit",
    "reservation.cancel",
    "reservation.assign_vehicle",
    "customer.view_basic",
    "customer.view_sensitive",
    "customer.edit",
    "vehicle.view",
    "vehicle.edit",
    "vehicle.inspect",
    "handover.override",
    "prep.view",
    "prep.manage",
    "payment.view",
    "payment.capture",
    "payment.refund",
    "finance.view",
    "finance.review",
    "finance.export",
    "finance.approve",
    "pricing.view",
    "audit.view",
    "ratings.view",
    "investor.view",
    "investor.manage",
  ],
  FIELD: ["reservation.view", "reservation.create", "customer.view_basic", "vehicle.view", "vehicle.inspect", "prep.view", "payment.view"],
  PREP: ["vehicle.view", "prep.view", "prep.manage"],
  FINANCE: ["reservation.view", "customer.view_basic", "payment.view", "payment.capture", "payment.refund", "pricing.view", "finance.view", "finance.review", "finance.export", "investor.view", "investor.finance"],
  SUPPORT: ["lead.view", "lead.edit", "inbox.view", "inbox.reply", "inbox.manage", "reservation.view", "customer.view_basic", "customer.edit"],
  VIEWER: ["reservation.view", "vehicle.view", "customer.view_basic", "payment.view", "pricing.view", "inbox.view"],
};

export function permissionsFor(roles: StaffRole[]) {
  return new Set(roles.flatMap((role) => rolePermissions[role] ?? []));
}
