export type Clause = { heading: string; paragraphs: string[] };

export type AgreementText = {
  brand: string;
  title: string;
  editionLine: string;
  edition: string;
  preface: string;
  labels: {
    entity: string;
    tradeName: string;
    edition: string;
    booking: string;
    executed: string;
    contractTerms: string;
    printedName: string;
    signature: string;
    signedAt: string;
    staffRecord: string;
    notProvided: string;
    pending: string;
    atSigning: string;
    yes: string;
    no: string;
    elected: string;
    declined: string;
    initials: string;
    electronicAccepted: string;
    electronicDeclined: string;
    systemRecord: string;
    disclosedHere: string;
    deliveredOnline: string;
  };
  clauses: Clause[];
  exhibitA: {
    title: string;
    intro: string;
    rows: {
      booking: string;
      entity: string;
      contact: string;
      emergency: string;
      renter: string;
      renterContact: string;
      license: string;
      otherDrivers: string;
      vehicle: string;
      plate: string;
      pickup: string;
      returnRow: string;
      days: string;
      discount: string;
      ageFee: string;
      deliveryFees: string;
      mileage: string;
      excess: string;
      soc: string;
      charging: string;
      waiver: string;
      taxes: string;
      totals: string;
      card: string;
      hold: string;
      extras: string;
      travel: string;
      changes: string;
    };
  };
  exhibitB: {
    title: string;
    warning: string;
    intro: string;
    rows: {
      category: string;
      unit: string;
      unitValue: string;
      decline: string;
      basic: string;
      standard: string;
      premier: string;
      selected: string;
      duplicate: string;
      oral: string;
      oralValue: string;
      posted: string;
    };
    tierValues: { decline: string; basic: string; standard: string; premier: string };
    exclusionsTitle: string;
    exclusions: string;
    attestation: string;
  };
  exhibitC: {
    title: string;
    intro: string;
    rows: {
      insurer: string;
      policyReference: string;
      effectiveDates: string;
      biLimits: string;
      propertyDamageLimit: string;
      deductible: string;
      driverCategories: string;
      territory: string;
      rentalEligibility: string;
      supplementalProducts: string;
      claimsContact: string;
      incidentPhone: string;
      ownerRelationship: string;
    };
    footer: string;
  };
  exhibitD: { title: string; note: string; footer: string };
  exhibitE: {
    title: string;
    warning: string;
    notice: string;
    rows: {
      locationInitials: string;
      oral: string;
      oralValue: string;
      returnDate: string;
      phone: string;
      election: string;
      channel: string;
      electionInitials: string;
      receipt: string;
    };
    footer: string;
  };
  exhibitF: {
    title: string;
    intro: string;
    rows: {
      duration: string;
      renewal: string;
      renewalValue: string;
      insurer: string;
      licensing: string;
      pricing: string;
      extensions: string;
      charging: string;
      holds: string;
      holdsValue: string;
      waiver: string;
      signatures: string;
    };
    footer: string;
  };
};
